- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 1h # Trauma was 2.5
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 2h # Trauma was 5
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 5h # Trauma was 10
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  supervisors: job-supervisors-captain
  #canBeAntag: false
  antagAdvantage: 75 # Goobstation
  guides: # goobstation
  - Engineering
  - Command
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: EngineeringStaff # Goobstation

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    id: CEPDA
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetAltEngineering # Goobstation
    belt: ClothingBeltUtilityEngineering
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation

- type: chameleonOutfit
  id: ChiefEngineerChameleonOutfit
  job: ChiefEngineer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretEngineering
    mask: ClothingMaskBreath
    neck: ClothingNeckCloakCe
    outerClothing: ClothingOuterWinterCE
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMagAdv
