- type: job
  id: Librarian
  name: job-name-librarian
  description: job-description-librarian
  playTimeTracker: JobLibrarian
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-hop
  access:
  - Library # Trauma - TODO, remove service after mapping is done
  - Service
  - Maintenance
  # <Trauma>
  special: # Librarian should speak most languages.
  - !type:AddImplantSpecial
    implants: [ LibrarianTranslatorImplant ]
  # </Trauma>
- type: startingGear
  id: LibrarianGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LibrarianPDA
    ears: ClothingHeadsetService
    pocket1: d20Dice
    pocket2: HandLabeler # for making named bestsellers
  storage:
    back:
    - BookRandom

- type: chameleonOutfit
  id: LibrarianChameleonOutfit
  job: Librarian
  equipment:
    head: ClothingHeadHatCanadaBeanie
    eyes: ClothingEyesGlassesJamjar
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedGreen
    outerClothing: ClothingOuterWinterColorGreen
    gloves: ClothingHandsGlovesColorBlack
